sudo: required

language: go

go:
  - "1.10"

addons:
  apt:
    packages:
      - docker-ce

script:
  - chmod +x test.sh
  - ./test.sh
  - CGO_ENABLED=0 go build
  - docker build --rm -t trigun117/news_aggregator .
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push trigun117/news_aggregator

after_success:
  - bash <(curl -s https://codecov.io/bash)